# language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t oreomini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oreomini/docker-react npm run test
